source 'https://rubygems.org'

gem 'rails', '4.2.6'
#gem 'sqlite3'
#gem 'sass-rails', '~> 5.0'
#gem 'uglifier', '>= 1.3.0'
#gem 'coffee-rails', '~> 4.1.0'
#gem 'jquery-rails'
#gem 'turbolinks'
#gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'rails-api'
gem 'active_model_serializers'
gem 'devise'
gem 'pg'
gem 'sidekiq'
gem 'sinatra', :require => nil

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'faker'
end
